"""update jobs fields

Revision ID: f32b159d6fd0
Revises: 
Create Date: 2023-03-12 23:20:28.416443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32b159d6fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('qualifications', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('qualifications')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
